[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CIDACS Clima - Data descriptor"
authors = [{name = "Cidacs Fiocruz", email = "cidacs@fiocruz.br"}]
dynamic = ["version", "description"]
